### ISSUE TITLE
default module mappings not working

### ISSUE THREAD

**Issue by IsmaelMartinez** [pantsbuild/example-python#120]
# Description

Trying to add the pythonjsonlogger into the example, to verify problems that I am having with my configuration. 

I added the pythonjsonlogger at the end of the [requirements.txt](https://github.com/pantsbuild/example-python/blob/main/requirements.txt) file 

```
python-json-logger==2.0.4
```

Then added the import statements into the [greetings.py](https://github.com/pantsbuild/example-python/blob/main/helloworld/greet/greeting.py#L8) file like this:

```
import logging
from pythonjsonlogger import jsonlogger
```

> I didn't define anything further from the logger as that is enough to validate the issue.

Then, tried running the `./pants test ::` command failed with the error

```
(.env) ➜  example-python git:(main) ✗ ./pants test ::                  
11:00:55.24 [INFO] Completed: Building 2 requirements for requirements.pex from the python-default.lock resolve: setuptools<57,>=56.2.0, types-setuptools<58,>=56.2.0
11:00:55.51 [INFO] Completed: Building 1 requirement for requirements.pex from the python-default.lock resolve: pytest==7.0.1
11:00:56.47 [ERROR] Completed: Run Pytest - helloworld/greet/greeting_test.py:tests failed (exit code 2).
============================= test session starts ==============================
platform darwin -- Python 3.9.16, pytest-7.0.1, pluggy-1.0.0
rootdir: /private/var/folders/0g/7yz8qfln279gr8gtr874hbvr1wzvx2/T/pants-sandbox-D7l7aI
plugins: xdist-2.5.0, forked-1.4.0, cov-3.0.0
collected 0 items / 1 error

==================================== ERRORS ====================================
______________ ERROR collecting helloworld/greet/greeting_test.py ______________
ImportError while importing test module '/private/var/folders/0g/7yz8qfln279gr8gtr874hbvr1wzvx2/T/pants-sandbox-D7l7aI/helloworld/greet/greeting_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
helloworld/greet/greeting_test.py:4: in <module>
    from helloworld.greet.greeting import Greeter
helloworld/greet/greeting.py:7: in <module>
    from pythonjsonlogger import jsonlogger
E   ModuleNotFoundError: No module named 'pythonjsonlogger'
- generated xml file: /private/var/folders/0g/7yz8qfln279gr8gtr874hbvr1wzvx2/T/pants-sandbox-D7l7aI/helloworld.greet.greeting_test.py.tests.xml -
=========================== short test summary info ============================
```

This failed to detect the default module_mappings described in the docs [use modules and module_mappings](https://www.pantsbuild.org/docs/python-third-party-dependencies#use-modules-and-module_mapping-when-the-module-name-is-not-standard) section.

I can see [pythonjsonlogger listed in the default ones ](https://github.com/pantsbuild/pants/blob/main/src/python/pants/backend/python/dependency_inference/default_module_mapping.py#L177)

Same happens with the poetry-requirements

# Expected behaviour

Expected to infer the module_mapping from the defaults

# Workaround

Current solution is to define the module mapping in the [base BUILD](https://github.com/pantsbuild/example-python/blob/main/BUILD) file like this:

```
python_requirements(
    name="reqs",
    module_mapping={"python-json-logger": ["pythonjsonlogger"]},
)
```

Once this is added, the system works. Hope helps!

**Comment by benjyw** [comment]
I assume you're not using a Pants 2.16 dev release? That module mapping was added in that version.

**Comment by IsmaelMartinez** [comment]
Just whatever comes with the demo. I guess this is fixed then. Thanks for the prompt response!
