### ISSUE TITLE
`setup-py` broke when adding codegen

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/example-python#27]
`./pants setup-py helloworld/util` results in:

```
ERROR: No exported target owner found for helloworld/protos
```

**Comment by benjyw** [comment]
This is because an exported target cannot export code that isn't below it in the filesystem. We can either make helloworld.protos its own distribution, or rearrange the structure slightly.

**Comment by Eric-Arellano** [comment]
Ah! Thanks Benjy. Either sounds fine to me. Another approach would be to move the distribution to live in `helloworld`, rather than `helloworld/util`?

I think I'd recommend having both `helloworld/protos` and `helloworld/util` because that's cool to demo how the ownership works, but I'll defer to you.

**Comment by benjyw** [comment]
Fixed in https://github.com/pantsbuild/example-python/pull/28
